services:
  - type: web
    name: vosk-transcriber
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg unzip wget
      pip install -r requirements.txt
    startCommand: python app.py
